[colors.primary]
background = "#121212"
foreground = "#f5f5f5"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
opacity = 1.0

[window.padding]
x = 16
y = 16
